<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ResearchProject" nsURI="ResearchProject" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//NamedElement #//TimedElement">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partners" lowerBound="1"
        upperBound="-1" eType="#//Partner" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workpackages" lowerBound="1"
        upperBound="-1" eType="#//Workpackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partner" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
      <details key="color" value="255,200,200"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efforts" lowerBound="1"
        upperBound="-1" eType="#//Effort" containment="true">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="0,0,0"/>
        <details key="label" value="Person/Months"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effort">
    <eAnnotations source="gmf.node">
      <details key="label" value="PersonMonths"/>
      <details key="figure" value="ellipse"/>
      <details key="color" value="200,255,200"/>
      <details key="phantom" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PersonMonths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="for_Workpackage" lowerBound="1"
        eType="#//Workpackage" eOpposite="#//Workpackage/packageEffort">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="0,0,0"/>
        <details key="label" value="for"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workpackage" eSuperTypes="#//NamedElement #//TimedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageEffort" lowerBound="1"
        upperBound="-1" eType="#//Effort" eOpposite="#//Effort/for_Workpackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliverables" lowerBound="1"
        upperBound="-1" eType="#//Deliverable" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//NamedElement #//TimedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
      <details key="color" value="200,200,255"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deliverable" eSuperTypes="#//NamedElement #//TimedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
      <details key="color" value="255,255,200"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
